# Generated by Django 3.0.4 on 2020-03-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
